// try {
//     // Code that may throw an exception
//     throw new Error('Something went wrong!');
// } catch (error) {
//     // Code to handle the exception
//     console.error('An error occurred:', error.message);
// }


// try {
//     // Code that may throw an exception
//     throw new Error('Something went wrong!');
// } catch (error) {
//     // Code to handle the exception
//     console.error('An error occurred:', error.message);
// } finally {
//     // Cleanup code that always executes
//     console.log('Cleanup code executed');
// }

